# Generated by Django 6.0 on 2025-12-22 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=100, unique=True)),
                ('description_categorie', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilite',
            fields=[
                ('id_vulnerabilite', models.AutoField(primary_key=True, serialize=False)),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('severite', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=20)),
                ('score_cvss', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('description_vuln', models.TextField()),
                ('date_publication', models.DateField()),
                ('source_vuln', models.CharField(max_length=100)),
                ('type_vuln', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vulnerabilite',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('titre_article', models.CharField(max_length=500)),
                ('url_article', models.URLField(max_length=1000, unique=True, validators=[django.core.validators.URLValidator()])),
                ('description_article', models.TextField(blank=True)),
                ('contenu_article', models.TextField(blank=True)),
                ('summary_article', models.TextField(blank=True)),
                ('date_publication', models.DateField()),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='backend.categorie')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=150, unique=True)),
                ('email_utilisateur', models.EmailField(max_length=254, unique=True)),
                ('role_utilisateur', models.CharField(choices=[('admin', 'Administrateur'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('categories_suivies', models.ManyToManyField(blank=True, related_name='utilisateurs_suivants', to='backend.categorie')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
    ]
