# Generated by Django 6.0 on 2025-12-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilite',
            name='contenu_vuln',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vulnerabilite',
            name='summary_vuln',
            field=models.TextField(blank=True),
        ),
    ]
