# Generated by Django 6.0.1 on 2026-01-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_vulnerabilite_severite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilite',
            name='severite',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique'), ('unknown', 'Inconnue')], max_length=20),
        ),
    ]
