# Generated by Django 6.0 on 2025-12-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_vulnerabilite_contenu_vuln_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilite',
            name='contenu_vuln',
        ),
        migrations.RemoveField(
            model_name='vulnerabilite',
            name='summary_vuln',
        ),
    ]
