# Generated by Django 6.0.1 on 2026-01-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_vulnerabilite_severite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role_utilisateur',
            field=models.CharField(choices=[('veilleur', 'Veilleur'), ('analyste', 'Analyste'), ('admin', 'Administrateur'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20),
        ),
    ]
