# Generated by Django 6.0.1 on 2026-01-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom_categorie']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['nom_source']},
        ),
    ]
